name: Bump version
on:   
  workflow_run:
    workflows: ["Compile test"]
    branches: [master]
    types:
      - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
                    
    - name: Generate changelog
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.18.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        skip-version-file: 'true'
        skip-on-empty: 'true'
        skip-commit: 'false'
            
    - name: Create release
      uses: actions/create-release@v1.1.4
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
    
    - name: Fix commit message
      id: step_one
      run: |
        echo "${{ github.event.workflow_run.head_commit.message }}" >> tmp.txt
        sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' tmp.txt >> reddacted.txt
        cat reddacted.txt
        COMMIT=$(<reddacted.txt)
        echo "COMMIT=$COMMIT" >> $GITHUB_ENV
          
    - name: Discord notification
      uses: rguillaume/discord-action-embed@v1.0.4
      with:
        webhook: ${{ secrets.UPDATES_WEBHOOK }}
        embed: '{"title": "Update: ${{ github.event.repository.name }}", "description": "${{ env.COMMIT }}", "url": "${{ github.event.workflow_run.repository.html_url }}/commit/${{ github.event.workflow_run.head_commit.id }}", "footer": {"text": "Committer: ${{ github.event.head_commit.author.name }}"}, "color": "16760576"}'
          
    - name: Merge to WaspLib-dev
      uses: everlytic/branch-merge@1.1.5
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      with:
        github_token: ${{ github.token }}
        source_ref: ${{ github.ref }}
        target_branch: 'dev'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'