name: Bump version
on:   
  workflow_run:
    workflows: ["Compile test"]
    branches: [master]
    types:
      - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
                    
    - name: Generate changelog
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.18.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        skip-version-file: 'true'
        skip-on-empty: 'true'
        skip-commit: 'false'
            
    - name: Create release
      uses: actions/create-release@v1.1.4
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
    
    - name: Discord notification
      uses: Sniddl/discord-commits@v1.5
      with:
        webhook: ${{ secrets.UPDATES_WEBHOOK }}
        template: "simple-link"
        embed: '{ "title": "Update: WaspLib", "description": "Committer: {{ commit.author.name }}\n\n**{{ commit.title }}**\n{{ commit.description }}", "url": "{{ commit.url }}"}'
    
    - name: Merge to WaspLib-dev
      uses: everlytic/branch-merge@1.1.5
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      with:
        github_token: ${{ github.token }}
        source_ref: ${{ github.ref }}
        target_branch: 'dev'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
        
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1.10.2
      with:
        webhook: ${{ secrets.UPDATES_WEBHOOK }}
        title: "WaspLib updated!"
        noprefix: true