name: Compile Test

on: [push, pull_request]      

env:
  simba-download: https://github.com/ollydev/Simba/releases/download/autobuild-simba1400/Simba-Win32.exe
  srl-download: https://github.com/Torwent/SRL.git

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      
      - name: Move files
        shell: bash
        run: mv ./ ./WaspLib/

      - name: Setup SRL
        shell: bash
        run: git clone ${{ env.srl-download }}

      - name: Move files
        shell: bash
        run: mv ./SRL/ ./Includes/SRL/ && mv ./WaspLib/ ./Includes/WaspLib/

      - name: Download Simba
        shell: bash
        run: curl --retry 5 -L -o Simba.exe ${{ env.simba-download }}

      - name: Directory tree
        run: tree
  
      - name: Compile Test
        shell: bash
        run: echo '{$I SRL/osr.simba}{$I WaspLib/osr.simba}' > test.simba && ./Simba.exe --compile test.simba
