name: Compile test

on: [push, pull_request]      

env:
  simba-download: https://github.com/ollydev/Simba/releases/download/simba1400-lape-update/Simba-Win32.exe
  srl-download: https://github.com/Torwent/SRL.git

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
      
      - name: Move files
        shell: bash
        run: |
          mkdir ./WaspLib
          for f in *; do if [ "./WaspLib" == "$f" ]; then continue; fi; mv "$f" "./WaspLib"; done

      - name: Setup SRL
        shell: bash
        run: git clone ${{ env.srl-download }}

      - name: Move files
        shell: bash
        run: |
          mkdir ./Includes
          mv ./SRL/ ./Includes/SRL/
          mv ./WaspLib/ ./Includes/WaspLib/

      - name: Download Simba
        shell: bash
        run: curl --retry 5 -L -o Simba.exe ${{ env.simba-download }}

      - name: Compile Test
        shell: bash
        run: |
          echo '{$I SRL/osr.simba}{$I WaspLib/osr.simba}' > test.simba
          ./Simba.exe --compile test.simba
