name: Releases

on: 
  workflow_run:
    workflows: ["Bump version"]
    branches: [master]
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
